import argparse

def cli_args():
    parser = argparse.ArgumentParser(
        description="A CLI tool to process MHTML files."
    )
    parser.add_argument(
        "-m", "--mhtml",
        type=str,
        required=True,
        help="path to the MHTML file to process"
    )
    parser.add_argument(
        "-k", "--keep",
        action="store_true",
        help="keep the 'tmp' directory content generated by previous runs (false by default)"
    )
    return parser.parse_args()
